### PR TITLE
Add WebPush encryption support

### PR DESCRIPTION
**Pull request by jtmcdole**
* Adds encryption support for WebPush
* Adds the example from rfc8291 section 5 (sanity check)
* Upgrades SDK version
* Unpins WebCrypto library

### CODE REVIEW

**Comment by karmanyaahm** [comment]
Very cool! Now we can publish this to pub.dev. Will take a look soon

**Comment by jtmcdole** [comment]
Awesome.  I've got a tiny dart server that does webpush now with this library!  I tried packaging it into a docker; but apparently WebCrypto requires Flutter (and thus dart docker doesn't work?) - so still trying to crack that nut.  Glad I could help.

Questions for improvement:
1- Should `WebPushKeys` be broken out to Public / Private versions?
2- Is there a way to ingest the private key as a raw EC?  I can do something like this with PointyCastle; which would match other online codelabs that generate keys.
```dart
  final webPushPrivateRaw = pc.ECPrivateKey(
      bytesToBigInt(
          base64Decode('iq-ocHLPqGnJpnM9GWOWZAJrlE0seZZNzFu5adTryV8=')),
      ECCurve_prime256v1());
```

That said; I don't really care much about 2 above because ultimately the only thing you send back is the public key and that's already in the correct format.

**Comment by jtmcdole** [comment]
Kind ping :)

**Comment by karmanyaahm** [comment]
Oops, my bad, missed the questions. 

1 - Yeah, I think it would be kind of nice from a client perspective to differentiate between public and private keys at compile time. But OTOH, if it's too much work, the current approach looks fine to me (current approach also keeps the library simple).
2 - I haven't touched this stuff (RFC 8188 and 8291) in a long long time, but sticking to the same convention as other generators sounds like a good idea. (I'm assuming this would also avoid having to run the `openssl pkcs8 -topk8 -in ec.priv -out my.pkcs8.key -nocrypt` command?)

**Comment by jwr1** [comment]
Could this be relooked at? I don't need encryption, but it would be nice if the deps & SDK versions were upgraded, and then this be published on pub.dev.

**Comment by jwr1** [comment]
I'd even be willing to make a separate pr with those changes if that's ok.

**Comment by p1gp1g** [comment]
Sure, feel free to open a pull request with the deps & SDK update.

**Comment by p1gp1g** [comment]
@jtmcdole I think we should separate pubkey/privkey/keypair (which would be WebPushKeys here) because decrypt should fail if this is not a keypair but a pubkey, same for encrypt if the server key is not a keypair

I'm OK to review this PR, so it can be merged soon :)

**Comment by jtmcdole** [comment]
It's been a while; let me see if I can reacquaint myself with this code :)

**Comment by jtmcdole** [comment]
Do you want to go ahead and make this a breaking change with the parameters being named?

**Comment by jtmcdole** [comment]
Please see #5 for review.

**Pull request closed without merging**
